### ISSUE TITLE
Error (?) when linting scss file

### ISSUE THREAD

**Issue by minikN** [skovhus/SublimeLinter-contrib-sass-lint#22]
Hello, when I format a scss file, this gets output into the console:

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 121, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 968, in lint_view
    linter.lint(hit_time)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1436, in lint
    output = self.run(cmd, self.code)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1843, in run
    return self.tmpfile(cmd, code)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1887, in tmpfile
    env=self.env)
  File "/Users/Artemios/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 1206, in tmpfile
    os.remove(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/nw/63ddhqvs7m12r8478ds5gr8r0000gn/T/SublimeLinter3-Artemios/layout.scss'
 
SublimeLinter: -------------------- 
```

But as far as I can see, the beautifying is working.

Settings:
```
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/Theme - Monokai Pro/Monokai_Classic/sublime_linter/Monokai Classic.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phpcs": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "standard": "PSR2"
            },
            "sass": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "use-server": false,
        "use_current_shell_path": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

The linting is working as far as I can see, however is this output expected?

OS: macOS 10.13.3
Sublime Text3 Build 3143

Thanks.

**Comment by skovhus** [comment]
Thanks for reporting this. I’m not really using `sass-lint` or Sublime anymore. 

Let me know if you figured out a solution, or if you want to look into submitting a PR for this.
