### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by fynncfchen** [skovhus/SublimeLinter-contrib-sass-lint#6]
OS: Windows
Sublime: Sublime Text 3

My console shows:

```
SublimeLinter: -------------------- 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\node_linter.py", line 77, in lint
    super(NodeLinter, self).lint(hit_time)
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\linter.py", line 1453, in lint
    start, end = self.highlight.full_line(line)
  File "D:\Sublime Text 3\Data\Packages\SublimeLinter\lint\highlight.py", line 200, in full_line
    start = self.newlines[line] + char_offset
IndexError: list index out of range
```

sass-lint plugin seems not work, but sass-lint CLI is work perfectly.

**Comment by skovhus** [comment]
@ethancfchen that seems like a bug deep down in SublimeLinter. To clarify this, please give me the exact scss-lint version that you are running.

**Comment by fynncfchen** [comment]
My `sass-lint` version is `1.5.0`, not _scss-lint_

**Comment by skovhus** [comment]
Sorry @ethancfchen, I cannot reproduce this. 

But I believe it isn't a bug related to SublimeLinter-contrib-sass-lint. So I guess you could try reinstalling sublime and sublime linter.
